### ISSUE TITLE
Testing Pretrained Models fail

### ISSUE THREAD

**Issue by hwLiu8** [mit-han-lab/spvnas#104] opened 2022-12-11 07:33 UTC
when i run this command : `torchpack dist-run -np 1 python evaluate.py configs/semantic_kitti/default.yaml --name SemanticKITTI_val_SPVNAS@65GMACs`  ,the terminel print: 

Segmentation fault (core dumped)

Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.

mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[34984,1],0]
  Exit code:    1

who knows how to solve this problem?  thanks.

**Comment by hwLiu8** [comment] 2022-12-11 14:55
When I delete these codes, no` Segmentation fault (core dumped)`error occurs
# from core.callbacks import MeanIoU
# from core.trainers import SemanticKITTITrainer
# from torchpack.callbacks import Callbacks, SaverRestore

why?

**Comment by zhijian-liu** [comment] 2022-12-16 20:41
This seems to be a duplicate of https://github.com/zhijian-liu/torchpack/issues/40.

**Closed** 2022-12-24 20:42 UTC
